// English, en-US
// This file was auto-generated by Quasalang

export default {
	// common
	"Add": `Add`,
	"Edit": `Edit`,
	"Delete": `Delete`,
	"View": `View`,
	"Cancel": `Cancel`,
	"Save": `Save`,
	"Back": `Back`,
	"Return": `Return`,
	"Search": `Search`,
	"Type your search text": `Type your search text`,
	"Filters": `Filters`,
	"Attachments": `Attachments`,
	"Status": `Status`,
	"Yes": `Yes`,
	"No": `No`,
	"All": `All`,
	"Pending": `Pending`,
	"Details": `Details`,
	"Photos": `Photos`,
	"Documents": `Documents`,
	"QR Code": `QR Code`,
	"Comments": `Comments`,
	"Timeline": `Timeline`,
	"Name": `Name`,
	"Description": `Description`,

	// login
	"Login": `Login`,
	"E-mail": `E-mail`,
	"Password": `Password`,
	"Error: Check username & password": `Error: Check username & password`,
	"Password confirmation": `Password confirmation`,
	"Remember me for 30 days": `Remember me for 30 days`,
	"Register": `Register`,
	"I need help": `I need help`,
	"Reset password": `Reset password`,
	"I accept the terms and conditions": `I accept the terms and conditions`,
	"Congratulations": `Congratulations`,
	"Almost done! Remember to confirm your email!": `Almost done! Remember to confirm your email!`,
	"First Name": `First Name`,
	"Last Name": `Last Name`,
	"NIP": `NIP`,
	"Company name": `Company name`,
	"Street": `Street`,
	"Postcode": `Postcode`,
	"City": `City`,
	"Last step": `Last step`,
	"Say something about yourself." : `Say something about yourself. `,
	"Lets start": `Lets start`,

	// files
	"Pick Video to upload": `Pick Video to upload`,
	"Pick Photo to upload": `Pick Photo to upload`,
	"Pick File to upload": `Pick File to upload`,
	"Delete Video": `Delete Video`,
	"Delete Photo": `Delete Photo`,
	"Delete File": `Delete File`,

	// dashboard
	"New": `New`,
	"Ongoing": `Ongoing`,
	"Paused": `Paused`,
	"Done": `Done`,
	"Rejected": `Rejected`,

	// users
	"Employee": `Employee`,
	"Employees": `Employees`,
	"First name": `First name`,
	"Last name": `Last name`,
	"Phone": `Phone`,
	"Age": `Age`,
	"New employee": `New employee`,

	// ideas
	"Ideas": `Ideas`,
	"Idea": `Idea`,
	"Idea title": `Idea title`,
	"Idea description": `Idea description`,
	"Your submission landed in our system": `Your submission landed in our system`,
	"Would you like to improve something more?": `Would you like to improve something more?`,
	"New idea": `New idea`,
	"Delete:": `Delete:`,
	"Deleted:": `Deleted:`,

	// issues
	"Issues": `Issues`,
	"Issue": `Issue`,
	"Issue name": `Issue name`,
	"Issue description": `Issue description`,
	"New issue": `New issue`,

	// items
	"Items": `Items`,
	"Item": `Item`,
	"Item title": `Item title`,
	"Item description": `Item description`,
	"New item": `New item`,

	// timeline
	"Issue added": `Issue added`,
	"Issue accepted": `Issue accepted`,
	"New person assigned to issue": `New person assigned to issue`,
	"Person removed from issue": `Person removed from issue`,
	"Issue started": `Issue started`,
	"Issue paused": `Issue paused`,
	"Issue resumed": `Issue resumed`,
	"Issue resolved": `Issue resolved`,


	// guides
	"Guides": `Guides`,
	"Guide": `Guide`,
	"New guide": `New guide`,
	"Guide name": `Guide name`,
	"Add new": `Add new`,

	// tasks
	"Action failed": `Action failed`,
	"Action was successful": `Action was successful`,
	"Work Time!": `Work Time!`,
	"Tasks": `Tasks`,
	"Your tasks": `Your tasks`,
	"All tasks": `All tasks`,
	"Task name": `Task name`,
	"Task description": `Task description`,

	// settings
	"Settings": `Settings`,
	"QR code": `QR code`,
	"Submission type": `Submission type`,
	"Anonymous": `Anonymous`,
	"Anonymous with required confirmation": `Anonymous with required confirmation`,
	"Only for logged users": `Only for logged users`,
	"You must have an account": `You must have an account`,

	// permissions
	"Permissions": `Permissions`,
	"Permission": `Permission`,
	"New permission": `New permission`,
	"Role": `Role`,

	// groups
	"Groups": `Groups`,
	"Group": `Group`,
	"New group": `New group`,
	"No groups, add a first one!": `No groups, add a first one!`,

	// TipTap
	"What's the title?": `What's the title?`,
	"Can you add some further context? Use @ to mention users, # for groups": `Can you add some further context? Use @ to mention users, # for groups`,
}