// English, en-US
// This file was auto-generated by Quasalang

export default {
	// login
	"Login": `Login`,
	"E-mail": `E-mail`,
	"Password": `Password`,
	"Password confirmation": `Password confirmation`,
	"Remember me for 30 days": `Remember me for 30 days`,
	"Register": `Register`,
	"I need help": `I need help`,
	"Reset password": `Reset password`,
	"I accept the terms and conditions": `I accept the terms and conditions`,


	// tasks
	"Action failed": `Action failed`,
	"Action was successful": `Action was successful`,
	"Work Time!": `Work Time!`,
	"Tasks": `Tasks`,
	"Your tasks": `Your tasks`,
	"All tasks": `All tasks`,
	"Task name": `Task name`,
	"Task description": `Task description`,
	"Add": `Add`,
	"Edit": `Edit`,
}