// English, en-US
// This file was auto-generated by Quasalang

export default {
	// login
	"Login": `Login`,
	"E-mail": `E-mail`,
	"Password": `Password`,
	"Password confirmation": `Password confirmation`,
	"Remember me for 30 days": `Remember me for 30 days`,
	"Register": `Register`,
	"I need help": `I need help`,
	"Reset password": `Reset password`,
	"I accept the terms and conditions": `I accept the terms and conditions`,
	"Congratulations": `Congratulations`,
	"Almost done! Let's confirm your email": `Almost done! Let's confirm your email`,
	"First Name": `First Name`,
	"Last Name": `Last Name`,
	"NIP": `NIP`,
	"Last step": `Last step`,
	"Say something about yourself." : `Say something about yourself. `,
	"Lets start": `Let's start`,

	// users
	"User": `User`,
	"Users": `Users`,
	"First name": `First name`,
	"Last name": `Last name`,
	"Phone": `Phone`,


	// Ideas
	"Ideas": `Ideas`,
	"Idea": `Idea`,
	"Idea title": `Idea title`,
	"Idea description": `Idea description`,



	// tasks
	"Action failed": `Action failed`,
	"Action was successful": `Action was successful`,
	"Work Time!": `Work Time!`,
	"Tasks": `Tasks`,
	"Your tasks": `Your tasks`,
	"All tasks": `All tasks`,
	"Task name": `Task name`,
	"Task description": `Task description`,
	"Add": `Add`,
	"Edit": `Edit`,
}