// German, de
// This file was auto-generated by Quasalang

export default {
	// login
	"Login": `Anmeldung`,
	"E-mail": `Email`,
	"Password": `Passwort`,
	"Password confirmation": `Passwort Bestätigung`,
	"Remember me for 30 days": `Erinnere dich für 30 Tage an mich`,
	"Register": `Registrieren`,
	"I need help": `Ich brauche Hilfe`,
	"Reset password": `Passwort zurücksetzen`,
	"I accept the terms and conditions": `Ich akzeptiere die allgemeinen Geschäftsbedingungen`,


	// tasks
	"Action failed": `Aktion: fehlgeschlagen`,
	"Action was successful": `Aktion war erfolgreich`,
	"Work Time!": `Arbeitszeit!`,
	"Tasks": `Aufgaben`,
	"Your tasks": `Ihre Aufgaben`,
	"All tasks": `Alle Aufgaben`,
	"Task name": `Aufgabennname`,
	"Task description": `Aufgabenbeschreibung`,
	"Add": `Addieren`,
	"Edit": `Bearbeiten`,
}