// German, de
// This file was auto-generated by Quasalang

export default {
	// common
	"Add": `Hinzufügen`,
	"Edit": `Bearbeiten`,
	"Delete": `Löschen`,
	"View": `Aussicht`,
	"Cancel": `Absagen`,
	"Save": `Speichern`,
	"Search": `Suche`,
	"Type your search text": `Geben Sie Ihren Suchtext ein`,
	"Filters": `Filter`,
	"Attachments": `Anhänge`,
	"Status": `Status`,
	"Yes": `Ja`,
	"No": `Nein`,
	"All": `Alle`,
	"Pending": `Ausstehend`,
	"Rejected": `Abgelehnt`,
	"Accepted": `Akzeptiert`,
	"Details": `Einzelheiten`,

	// login
	"Login": `Anmeldung`,
	"E-mail": `Email`,
	"Password": `Passwort`,
	"Error: Check username & password": `Fehler: Benutzername und Passwort überprüfen`,
	"Password confirmation": `Passwort Bestätigung`,
	"Remember me for 30 days": `Erinnere dich für 30 Tage an mich`,
	"Register": `Registrieren`,
	"I need help": `Ich brauche Hilfe`,
	"Reset password": `Passwort zurücksetzen`,
	"I accept the terms and conditions": `Ich akzeptiere die allgemeinen Geschäftsbedingungen`,
	"Congratulations": `Herzliche Glückwünsche`,
	"Almost done! Remember to confirm your email!": `Fast fertig! Denken Sie daran, Ihre E -Mail zu bestätigen!`,
	"First Name": `Vorname`,
	"Last Name": `Nachname`,
	"NIP": `NIP`,
	"Company name": `Name der Firma`,
	"Street": `Straße`,
	"Postcode": `Postleitzahl`,
	"City": `Stadt`,
	"Last step": `Letzter Schritt`,
	"Say something about yourself." : `Sage etwas über dich selbst.`,
	"Lets start": `Lasst uns beginnen`,

	// files
	"Pick Video to upload": `Video zum Hochladen auswählen`,
	"Pick Photo to upload": `Foto zum Hochladen auswählen`,
	"Delete Video": `Video löschen`,
	"Delete Photo": `Foto löschen`,

	// dashboard
	"New": `Neu`,
	"Voted": `Gewählt`,
	"Accepted": `Akzeptiert`,
	"Rejected": `Abgelehnt`,

	// users
	"Employee": `Angestellter`,
	"Employees": `Angestellte`,
	"First name": `Vorname`,
	"Last name": `Nachname`,
	"Phone": `Telefon`,
	"Name": `Name`,
	"Age": `Das Alter`,
	"New employee": `Neuer Angestellter`,

	// ideas
	"Ideas": `Ideen`,
	"Idea": `Idee`,
	"Idea title": `Ideenentitel`,
	"Idea description": `Ideenbeschreibung`,
	"Your submission landed in our system": `Ihre Einreichung landete in unserem System`,
	"Would you like to improve something more?": `Möchten Sie etwas mehr verbessern?`,
	"New idea": `Neue Idee`,

	// Guides
	"Guides": `Führer`,
	"Guide": `Führen`,
	"New guide": `Neuer Leitfaden`,
	"Guide name": `Leitfadenname`,

	// tasks
	"Action failed": `Aktion: fehlgeschlagen`,
	"Action was successful": `Aktion war erfolgreich`,
	"Work Time!": `Arbeitszeit!`,
	"Tasks": `Aufgaben`,
	"Your tasks": `Ihre Aufgaben`,
	"All tasks": `Alle Aufgaben`,
	"Task name": `Aufgabennname`,
	"Task description": `Aufgabenbeschreibung`,

	// settings
	"Settings": `Einstellungen`,
	"QR code": `QR-Code`,
	"Submission type": `Einreichungstyp`,
	"Anonymous": `Anonym`,
	"Anonymous with required confirmation": `Anonymous mit der erforderlichen Bestätigung`,
	"Only for logged users": `Nur für protokollierte Benutzer`,
	"You must have an account": `Sie müssen ein Konto haben`,
	"Ideas": `Ideen`,
	"Permissions": `Berechtigungen`,
	"Groups": `Gruppen`,

	// permissions
	"Permissions": `Berechtigungen`,
	"Permission": `Genehmigung`,
	"New permission": `Neue Erlaubnis`,
	"Name": `Name`,
	"Description": `Beschreibung`,
	"Role": `Rolle`,

	// groups
	"Groups": `Gruppen`,
	"Group": `Gruppe`,
	"New group": `Neue Gruppe`,
	"Name": `Name`,
	"Description": `Beschreibung`,
	"No groups, add a first one!": `Keine Gruppen, füge einen ersten hinzu!`,

	// TipTap
	"What's the title?": `Wie lautet der Titel?`,
	"Can you add some further context? Use @ to mention users, # for groups": `Können Sie einen weiteren Kontext hinzufügen? Verwenden Sie @, um Benutzer zu erwähnen, # für Gruppen`,
}