// German, de
// This file was auto-generated by Quasalang

export default {
	// common
	"Add": `Hinzufügen`,
	"Edit": `Bearbeiten`,
	"Delete": `Löschen`,
	"View": `Sicht`,
	"Cancel": `Stornieren`,
	"Save": `Speichern`,
	"Back": `Zurück`,
	"Return": `Zurückkehren`,
	"Search": `Suchen`,
	"Type your search text": `Geben Sie Ihren Suchtext ein`,
	"Filters": `Filter`,
	"Attachments": `Anhänge`,
	"Status": `Status`,
	"Yes": `Ja`,
	"No": `NEIN`,
	"All": `Alle`,
	"Pending": `Ausstehend`,
	"Details": `Einzelheiten`,
	"Photos": `Fotos`,
	"Documents": `Unterlagen`,
	"QR Code": `QR-Code`,
	"Comments": `Kommentare`,
	"Timeline": `Zeitleiste`,
	"Name": `Name`,
	"Description": `Beschreibung`,
	"New": `Neu`,
	"Active": `Aktiv`,
	"Inactive": `Inaktiv`,
	"Accepted": `Akzeptiert`,
	"Rejected": `Abgelehnt`,
	"In progress": `Im Gange`,
	"Paused": `Blättern`,
	"Resolved": `Beschlossen`,
	"Yesterday": `Gestern`,
	"Today": `Heute`,
	"Week": `Woche`,
	"Month": `Monat`,
	"Custom": `Brauch`,

	// login
	"Login": `Anmeldung`,
	"E-mail": `Email`,
	"Password": `Passwort`,
	"Error: Check username & password": `Fehler: Benutzername und Passwort überprüfen`,
	"Password confirmation": `Passwort Bestätigung`,
	"Remember me for 30 days": `Erinnere dich für 30 Tage an mich`,
	"Register": `Registrieren`,
	"I need help": `Ich brauche Hilfe`,
	"Reset password": `Passwort zurücksetzen`,
	"I accept the terms and conditions": `Ich akzeptiere die allgemeinen Geschäftsbedingungen`,
	"Congratulations": `Glückwunsch`,
	"Almost done! Remember to confirm your email!": `Fast fertig! Denken Sie daran, Ihre E -Mail zu bestätigen!`,
	"First Name": `Vorname`,
	"Last Name": `Familienname, Nachname`,
	"NIP": `NIP`,
	"Company name": `Name der Firma`,
	"Street": `Straße`,
	"Postcode": `Postleitzahl`,
	"City": `Stadt`,
	"Last step": `Letzter Schritt`,
	"Say something about yourself." : `Sage etwas über dich selbst.`,
	"Lets start": `Lasst uns beginnen`,

	// files
	"Pick Video to upload": `Video zum Hochladen auswählen`,
	"Pick Photo to upload": `Foto zum Hochladen auswählen`,
	"Pick File to upload": `Datei zum Hochladen auswählen`,
	"Delete Video": `Video löschen`,
	"Delete Photo": `Foto löschen`,
	"Delete File": `Datei löschen`,

	// dashboard
	"New": `Neu`,
	"Ongoing": `Laufend`,
	"Paused": `Blättern`,
	"Done": `Erledigt`,
	"Rejected": `Abgelehnt`,

	// users
	"Employee": `Mitarbeiter`,
	"Employees": `Mitarbeiter`,
	"First name": `Vorname`,
	"Last name": `Familienname, Nachname`,
	"Phone": `Telefon`,
	"Age": `Alter`,
	"New employee": `Neuer Angestellter`,

	// ideas
	"Ideas": `Ideen`,
	"Idea": `Idee`,
	"Idea title": `Ideenentitel`,
	"Idea description": `Ideenbeschreibung`,
	"Your submission landed in our system": `Ihre Einreichung landete in unserem System`,
	"Would you like to improve something more?": `Möchten Sie etwas mehr verbessern?`,
	"New idea": `Neue Idee`,
	"Delete:": `Löschen:`,
	"Deleted:": `Gelöscht:`,

	// issues
	"Issues": `Themen`,
	"Issue": `Ausgabe`,
	"Issue name": `Ausgabename`,
	"Issue description": `Fehlerbeschreibung`,
	"New issue": `Neues Problem`,

	// items
	"Items": `Artikel`,
	"Item": `Artikel`,
	"Item title": `Artikeltitel`,
	"Item description": `Artikelbeschreibung`,
	"New item": `Neuer Gegenstand`,

	// timeline
	"Issue added": `Problem hinzugefügt`,
	"Issue accepted": `Ausgabe akzeptiert`,
	"Issue rejected": `Problem abgelehnt`,
	"New person assigned to issue": `Neue Person, die zur Ausgabe zugewiesen ist`,
	"Person removed from issue": `Person von der Ausgabe entfernt`,
	"Issue started": `Das Problem begann`,
	"Issue paused": `Ausgabe machte eine Pause`,
	"Issue resumed": `Problem wieder aufgenommen`,
	"Issue resolved": `Problem gelöst`,

	// guides
	"Guides": `Führer`,
	"Guide": `Führung`,
	"New guide": `Neuer Leitfaden`,
	"Guide name": `Leitfadenname`,
	"Add new": `Neue hinzufügen`,

	// tasks
	"Action failed": `Aktion: fehlgeschlagen`,
	"Action was successful": `Aktion war erfolgreich`,
	"Work Time!": `Arbeitszeit!`,
	"Tasks": `Aufgaben`,
	"Your tasks": `Ihre Aufgaben`,
	"All tasks": `Alle Aufgaben`,
	"Task name": `Aufgabennname`,
	"Task description": `Aufgabenbeschreibung`,

	// settings
	"Settings": `Einstellungen`,
	"QR code": `QR-Code`,
	"Submission type": `Einreichungstyp`,
	"Anonymous": `Anonym`,
	"Anonymous with required confirmation": `Anonymous mit der erforderlichen Bestätigung`,
	"Only for logged users": `Nur für protokollierte Benutzer`,
	"You must have an account": `Sie müssen ein Konto haben`,

	// permissions
	"Permissions": `Berechtigungen`,
	"Permission": `Erlaubnis`,
	"New permission": `Neue Erlaubnis`,
	"Role": `Rolle`,

	// roles
	"Admin": `Administrator`,
	"Main admin": `Hauptadmin`,

	// groups
	"Groups": `Gruppen`,
	"Group": `Gruppe`,
	"New group": `Neue Gruppe`,
	"No groups, add a first one!": `Keine Gruppen, füge einen ersten hinzu!`,

	// TipTap
	"What's the title?": `Wie lautet der Titel?`,
	"Can you add some further context? Use @ to mention users, # for groups": `Können Sie einen weiteren Kontext hinzufügen? Verwenden Sie @, um Benutzer zu erwähnen, # für Gruppen`,
}