// French, fr
// This file was auto-generated by Quasalang

export default {
	// common
	"Add": `Ajouter`,
	"Edit": `Éditer`,
	"Delete": `Effacer`,
	"View": `Voir`,
	"Cancel": `Annuler`,
	"Save": `sauvegarder`,
	"Search": `Chercher`,
	"Type your search text": `Tapez votre texte de recherche`,
	"Filters": `Filtres`,
	"Attachments": `Attachements`,
	"Status": `Statut`,
	"Yes": `Oui`,
	"No": `Non`,
	"All": `Tout`,
	"Pending": `En attente`,
	"Rejected": `Rejeté`,
	"Accepted": `Accepté`,
	"Details": `Détails`,

	// login
	"Login": `Connexion`,
	"E-mail": `E-mail`,
	"Password": `Mot de passe`,
	"Error: Check username & password": `Erreur: vérifiez le nom d'utilisateur et le mot de passe`,
	"Password confirmation": `Confirmation mot de passe`,
	"Remember me for 30 days": `Souviens-toi de moi pendant 30 jours`,
	"Register": `S'inscrire`,
	"I need help": `j'ai besoin d'aide`,
	"Reset password": `Réinitialiser le mot de passe`,
	"I accept the terms and conditions": `J'accepte les termes et conditions`,
	"Congratulations": `Toutes nos félicitations`,
	"Almost done! Remember to confirm your email!": `Presque fini! N'oubliez pas de confirmer votre e-mail!`,
	"First Name": `Prénom`,
	"Last Name": `Nom de famille`,
	"NIP": `NIP`,
	"Company name": `Nom de l'entreprise`,
	"Street": `Rue`,
	"Postcode": `Code postal`,
	"City": `Ville`,
	"Last step": `Dernière étape`,
	"Say something about yourself." : `Dites quelque chose à propos de vous.`,
	"Lets start": `Commençons`,

	// files
	"Pick Video to upload": `Choisissez la vidéo à télécharger`,
	"Pick Photo to upload": `Choisissez la photo pour télécharger`,
	"Delete Video": `Supprimer la vidéo`,
	"Delete Photo": `Supprimer la photo`,

	// dashboard
	"New": `Nouveau`,
	"Voted": `Voté`,
	"Accepted": `Accepté`,
	"Rejected": `Rejeté`,

	// users
	"Employee": `Employé`,
	"Employees": `Des employés`,
	"First name": `Prénom`,
	"Last name": `Nom de famille`,
	"Phone": `Téléphoner`,
	"Name": `Nom`,
	"Age": `Âge`,
	"New employee": `Nouvel employé`,

	// ideas
	"Ideas": `Idées`,
	"Idea": `Idée`,
	"Idea title": `Titre d'idée`,
	"Idea description": `Description de l'idée`,
	"Your submission landed in our system": `Votre soumission a atterri dans notre système`,
	"Would you like to improve something more?": `Souhaitez-vous améliorer quelque chose de plus?`,
	"New idea": `Nouvelle idée`,

	// Guides
	"Guides": `Guides`,
	"Guide": `Guide`,
	"New guide": `Nouveau guide`,
	"Guide name": `Nom de guide`,

	// tasks
	"Action failed": `Action: échoué`,
	"Action was successful": `L'action a réussi`,
	"Work Time!": `Temps de travail!`,
	"Tasks": `Tâches`,
	"Your tasks": `Vos tâches`,
	"All tasks": `Toutes les tâches`,
	"Task name": `Nom de la tâche`,
	"Task description": `Description de la tâche`,

	// settings
	"Settings": `Réglages`,
	"QR code": `QR Code`,
	"Submission type": `Type de soumission`,
	"Anonymous": `Anonyme`,
	"Anonymous with required confirmation": `Anonyme de confirmation requise`,
	"Only for logged users": `Uniquement pour les utilisateurs enregistrés`,
	"You must have an account": `Vous devez avoir un compte`,
	"Ideas": `Idées`,
	"Permissions": `Autorisation`,
	"Groups": `Groupes`,

	// permissions
	"Permissions": `Autorisation`,
	"Permission": `Autorisation`,
	"New permission": `Nouvelle autorisation`,
	"Name": `Nom`,
	"Description": `La description`,
	"Role": `Rôle`,

	// groups
	"Groups": `Groupes`,
	"Group": `Groupe`,
	"New group": `Nouveau groupe`,
	"Name": `Nom`,
	"Description": `La description`,
	"No groups, add a first one!": `Pas de groupes, ajoutez-en un premier!`,

	// TipTap
	"What's the title?": `Quel est le titre?`,
	"Can you add some further context? Use @ to mention users, # for groups": `Pouvez-vous ajouter un contexte supplémentaire? Utiliser @ pour mentionner les utilisateurs, # pour les groupes`,
}