// French, fr
// This file was auto-generated by Quasalang

export default {
	// login
	"Login": `Connexion`,
	"E-mail": `E-mail`,
	"Password": `Mot de passe`,
	"Password confirmation": `Confirmation mot de passe`,
	"Remember me for 30 days": `Souviens-toi de moi pendant 30 jours`,
	"Register": `S'inscrire`,
	"I need help": `j'ai besoin d'aide`,
	"Reset password": `Réinitialiser le mot de passe`,
	"I accept the terms and conditions": `J'accepte les termes et conditions`,
	"Congratulations": `Toutes nos félicitations`,
	"Almost done! Let's confirm your email": `Presque fini! Confirmons votre email`,
	"First Name": `Prénom`,
	"Last Name": `Nom de famille`,
	"NIP": `NIP`,
	"Last step": `Dernière étape`,
	"Say something about yourself." : `Dites quelque chose à propos de vous.`,
	"Lets start": `Commençons`,

	// tasks
	"Action failed": `Action: échoué`,
	"Action was successful": `L'action a réussi`,
	"Work Time!": `Temps de travail!`,
	"Tasks": `Tâches`,
	"Your tasks": `Vos tâches`,
	"All tasks": `Toutes les tâches`,
	"Task name": `Nom de la tâche`,
	"Task description": `Description de la tâche`,
	"Add": `Ajouter`,
	"Edit": `Éditer`,
}