// Polish, pl
// This file was auto-generated by Quasalang

export default {
	// common
	"Add": `Dodaj`,
	"Edit": `Edytuj`,
	"View": `Podgląd`,
	"Cancel": `Anuluj`,
	"Save": `Zapisz`,
	"Search": `Szukaj`,
	"Type your search text": `Wpisz swój tekst wyszukiwania`,
	"Filters": `Filtry`,
	"Attachments": `Załączniki`,
	"Status": `Status`,
	"Yes": `Tak`,
	"No": `Nie`,
	"All": `Wszystko`,
	"Pending": `W oczekiwaniu`,
	"Rejected": `Odrzucony`,
	"Accepted": `Przyjęty`,

	// login
	"Login": `Zaloguj sie`,
	"E-mail": `E-mail`,
	"Password": `Hasło`,
	"Error: Check username & password": `Błąd: Sprawdź nazwę użytkownika i hasło`,
	"Password confirmation": `Potwierdzenie hasła`,
	"Remember me for 30 days": `Pamiętaj o mnie przez 30 dni`,
	"Register": `Zarejstruj się`,
	"I need help": `Potrzebuję pomocy`,
	"Reset password": `Zresetuj hasło`,
	"I accept the terms and conditions": `Akceptuję zasady i warunki`,
	"Congratulations": `Gratulacje`,
	"Almost done! Remember to confirm your email!": `Prawie skończone! Pamiętaj, aby potwierdzić swój e -mail!`,
	"First Name": `Imię`,
	"Last Name": `Nazwisko`,
	"NIP": `NIP`,
	"Last step": `Ostatni krok`,
	"Say something about yourself." : `Powiedz coś o sobie.`,
	"Lets start": `Zaczynajmy`,

	// dashboard
	"New": `Nowy`,
	"Voted": `Głosował`,
	"Accepted": `Przyjęty`,
	"Rejected": `Odrzucony`,

	// users
	"Employee": `Pracownik`,
	"Employees": `Pracownicy`,
	"First name": `Imię`,
	"Last name": `Nazwisko`,
	"Phone": `Telefon`,
	"Name": `Nazwa`,
	"Age": `Wiek`,
	"New employee": `Nowy pracownik`,

	// ideas
	"Ideas": `Pomysły`,
	"Idea": `Pomysł`,
	"Idea title": `Tytuł pomysłu`,
	"Idea description": `Opis pomysłu`,
	"Your submission landed in our system": `Twoje zgłoszenie wylądowało w naszym systemie`,
	"Would you like to improve something more?": `Czy chciałbyś poprawić coś więcej?`,
	"New idea": `Nowy pomysł`,

	// Guides
	"Guides": `Przewodniki`,
	"Guide": `Przewodnik`,
	"New guide": `Nowy przewodnik`,

	// tasks
	"Action failed": `Akcja: nieudana`,
	"Action was successful": `Działanie zakończyło się sukcesem`,
	"Work Time!": `Czas pracy!`,
	"Tasks": `Zadania`,
	"Your tasks": `Twoje zadania`,
	"All tasks": `Wszystkie zadania`,
	"Task name": `Nazwa zadania`,
	"Task description": `Opis zadania`,

	// settings
	"Settings": `Ustawienia`,
	"QR code": `Kod QR`,
	"Submission type": `Typ zgłoszenia`,
	"Anonymous": `Anonimowy`,
	"Anonymous with required confirmation": `Anonimowy z wymaganym potwierdzeniem`,
	"Only for logged users": `Tylko dla zalogowanych użytkowników`,
	"You must have an account": `Musisz mieć konto`,
	"Ideas": `Pomysły`,
	"Permissions": `Uprawnienia`,
	"Groups": `Grupy`,

	// permissions
	"Permissions": `Uprawnienia`,
	"Permission": `Pozwolenie`,
	"New permission": `Nowe pozwolenie`,
	"Name": `Nazwa`,
	"Description": `Opis`,

	// groups
	"Groups": `Grupy`,
	"Group": `Grupa`,
	"New group": `Nowa grupa`,
	"Name": `Nazwa`,
	"Description": `Opis`,
	"No groups, add a first one!": `Bez grup, dodaj pierwszy!`,

	// TipTap
	"What's the title?": `Jaki jest tytuł?`,
	"Can you add some further context? Use @ to mention users, # for groups": `Czy możesz dodać jakiś dalszy kontekst? Użyj @, aby wspomnieć o użytkownikach, # dla grup`,
}