// Polish, pl
// This file was auto-generated by Quasalang

export default {
	// login
	"Login": `Zaloguj sie`,
	"E-mail": `E-mail`,
	"Password": `Hasło`,
	"Password confirmation": `Potwierdzenie hasła`,
	"Remember me for 30 days": `Zapamiętaj mnie przez 30 dni`,
	"Register": `Zarejestrować`,
	"I need help": `potrzebuję pomocy`,
	"Reset password": `Zresetuj hasło`,
	"I accept the terms and conditions": `Akceptuję zasady i warunki`,
	"Congratulations": `Gratulacje`,
	"Almost done! Let's confirm your email": `Prawie skończone! Potwierdźmy Twój e-mail`,
	"First Name": `Imię`,
	"Last Name": `Nazwisko`,
	"NIP": `NIP`,
	"Last step": `Ostatni krok`,
	"Say something about yourself." : `Powiedz coś o sobie.`,
	"Lets start": `Zaczynajmy`,

	// tasks
	"Action failed": `Akcja: nieudana`,
	"Action was successful": `Działanie powiodło się`,
	"Work Time!": `Czas pracy!`,
	"Tasks": `Zadania`,
	"Your tasks": `Twoje zadania`,
	"All tasks": `Wszystkie zadania`,
	"Task name": `Nazwa zadania`,
	"Task description": `Opis zadania`,
	"Add": `Dodać`,
	"Edit": `Edytować`,
}